export default [
  {
    _id: '5c1d5125d78a4a7f27bf1e5b',
    index: 0,
    guid: '3b9e4d8d-bb88-46af-b0b3-e0635b9c2699',
    isActive: true,
    balance: '$3,202.83',
    picture: 'http://placehold.it/32x32',
    age: 34,
    eyeColor: 'green',
    name: {
      first: 'Calderon',
      last: 'Golden',
    },
    company: 'BICOL',
    email: 'calderon.golden@bicol.io',
    phone: '+1 (820) 470-3152',
    address: '669 Sands Street, Farmington, New York, 4173',
    about:
      'Magna ad et amet sunt veniam occaecat. Voluptate veniam est anim adipisicing excepteur excepteur fugiat fugiat laboris culpa magna est irure. Et ex duis laborum id adipisicing dolore Lorem irure esse in nulla id culpa. Nulla aute qui sunt dolore est esse deserunt amet pariatur ex ipsum et. Anim amet anim in ex cupidatat culpa aliqua ea fugiat occaecat proident.',
    registered: 'Tuesday, September 11, 2018 6:47 AM',
    latitude: '-59.260216',
    longitude: '-123.547528',
    tags: ['labore', 'sunt', 'veniam', 'ipsum', 'proident'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Dorthy Ayala',
      },
      {
        id: 1,
        name: 'Wood Sharpe',
      },
      {
        id: 2,
        name: 'Ruthie Hoover',
      },
    ],
    greeting: 'Hello, Calderon! You have 6 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5c1d51253c239773aef819b3',
    index: 1,
    guid: '57c60701-3213-41bd-a7f2-a5ff91241826',
    isActive: true,
    balance: '$2,796.43',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'blue',
    name: {
      first: 'Monroe',
      last: 'Gibbs',
    },
    company: 'ANARCO',
    email: 'monroe.gibbs@anarco.us',
    phone: '+1 (919) 523-2250',
    address: '357 Dank Court, Chloride, Guam, 1791',
    about:
      'Sint dolor ad adipisicing enim fugiat duis. Veniam incididunt ut laboris nisi aliqua incididunt proident duis nisi Lorem adipisicing et. Laboris voluptate minim cillum proident eiusmod sint anim. Consectetur mollit deserunt do occaecat cupidatat tempor do reprehenderit sunt aute ut veniam ullamco. Aliquip sit excepteur ex mollit duis esse. Cupidatat ipsum laborum cillum aute nisi irure voluptate esse nostrud nulla do qui.',
    registered: 'Sunday, August 6, 2017 2:34 PM',
    latitude: '-78.334808',
    longitude: '-54.971123',
    tags: ['aliquip', 'exercitation', 'in', 'esse', 'dolor'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Sybil Herring',
      },
      {
        id: 1,
        name: 'Pena Daniel',
      },
      {
        id: 2,
        name: 'Sellers Macdonald',
      },
    ],
    greeting: 'Hello, Monroe! You have 8 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '5c1d5125d30088b5ad55d663',
    index: 2,
    guid: '6c1dd33b-79f7-471b-be02-9fcdcdf7352c',
    isActive: false,
    balance: '$1,091.84',
    picture: 'http://placehold.it/32x32',
    age: 39,
    eyeColor: 'blue',
    name: {
      first: 'Charlene',
      last: 'Dotson',
    },
    company: 'TECHMANIA',
    email: 'charlene.dotson@techmania.com',
    phone: '+1 (922) 545-2119',
    address: '701 Fiske Place, Brewster, Virgin Islands, 5348',
    about:
      'Laboris aliquip ex consequat duis. Incididunt et laboris velit ipsum. Cillum nulla aute eu qui incididunt minim deserunt ullamco velit. Occaecat enim eu ex do aliqua sit. Id culpa ea labore dolor incididunt in ad eiusmod fugiat minim. Id ad excepteur laborum fugiat ex mollit.',
    registered: 'Sunday, June 26, 2016 6:15 PM',
    latitude: '15.117944',
    longitude: '-37.21466',
    tags: ['minim', 'do', 'tempor', 'et', 'tempor'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Burch Dudley',
      },
      {
        id: 1,
        name: 'Taylor Bradford',
      },
      {
        id: 2,
        name: 'Burton Brennan',
      },
    ],
    greeting: 'Hello, Charlene! You have 10 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '5c1d5125963396c84db3c2e0',
    index: 3,
    guid: '616c76f8-56df-41c6-bbd9-bd414fcadc14',
    isActive: false,
    balance: '$1,146.36',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'green',
    name: {
      first: 'Maddox',
      last: 'Chan',
    },
    company: 'INSURITY',
    email: 'maddox.chan@insurity.name',
    phone: '+1 (880) 402-2289',
    address: '116 Wythe Avenue, Kilbourne, Oregon, 1806',
    about:
      'Ea eu voluptate sunt commodo aute culpa qui do amet enim nulla excepteur. Pariatur exercitation ut sint aliqua amet fugiat deserunt commodo laborum amet. Aute voluptate amet non fugiat magna ea est laborum elit magna Lorem consectetur Lorem excepteur.',
    registered: 'Thursday, June 9, 2016 2:44 PM',
    latitude: '14.830267',
    longitude: '75.418401',
    tags: ['laboris', 'tempor', 'mollit', 'proident', 'aliqua'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Nolan Silva',
      },
      {
        id: 1,
        name: 'Hardy Gentry',
      },
      {
        id: 2,
        name: 'Mendez Bass',
      },
    ],
    greeting: 'Hello, Maddox! You have 7 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5c1d5125a0ea44a92fa747e4',
    index: 4,
    guid: '77ad319a-1b03-4936-ae70-7ae168dfee68',
    isActive: false,
    balance: '$1,820.02',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'blue',
    name: {
      first: 'Harriet',
      last: 'Bolton',
    },
    company: 'ONTALITY',
    email: 'harriet.bolton@ontality.info',
    phone: '+1 (957) 516-3516',
    address: '431 Lombardy Street, Manchester, Pennsylvania, 161',
    about:
      'Ullamco laboris laboris irure velit elit dolore commodo. Ut mollit nulla consectetur nisi nisi in incididunt. Labore enim incididunt consectetur commodo id. Sit fugiat dolor quis amet aliqua aliquip ut. Aliqua nulla elit excepteur dolor. Quis laboris excepteur consequat ipsum cupidatat magna culpa.',
    registered: 'Sunday, July 31, 2016 10:16 AM',
    latitude: '12.980598',
    longitude: '165.643823',
    tags: ['duis', 'veniam', 'aliquip', 'deserunt', 'duis'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Effie Kramer',
      },
      {
        id: 1,
        name: 'Wilda Moss',
      },
      {
        id: 2,
        name: 'Katie Brown',
      },
    ],
    greeting: 'Hello, Harriet! You have 10 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5c1d5125d78a4a7f27bf1e5b',
    index: 0,
    guid: '3b9e4d8d-bb88-46af-b0b3-e0635b9c2699',
    isActive: true,
    balance: '$3,202.83',
    picture: 'http://placehold.it/32x32',
    age: 34,
    eyeColor: 'green',
    name: {
      first: 'Calderon',
      last: 'Golden',
    },
    company: 'BICOL',
    email: 'calderon.golden@bicol.io',
    phone: '+1 (820) 470-3152',
    address: '669 Sands Street, Farmington, New York, 4173',
    about:
      'Magna ad et amet sunt veniam occaecat. Voluptate veniam est anim adipisicing excepteur excepteur fugiat fugiat laboris culpa magna est irure. Et ex duis laborum id adipisicing dolore Lorem irure esse in nulla id culpa. Nulla aute qui sunt dolore est esse deserunt amet pariatur ex ipsum et. Anim amet anim in ex cupidatat culpa aliqua ea fugiat occaecat proident.',
    registered: 'Tuesday, September 11, 2018 6:47 AM',
    latitude: '-59.260216',
    longitude: '-123.547528',
    tags: ['labore', 'sunt', 'veniam', 'ipsum', 'proident'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Dorthy Ayala',
      },
      {
        id: 1,
        name: 'Wood Sharpe',
      },
      {
        id: 2,
        name: 'Ruthie Hoover',
      },
    ],
    greeting: 'Hello, Calderon! You have 6 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5c1d51253c239773aef819b3',
    index: 1,
    guid: '57c60701-3213-41bd-a7f2-a5ff91241826',
    isActive: true,
    balance: '$2,796.43',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'blue',
    name: {
      first: 'Monroe',
      last: 'Gibbs',
    },
    company: 'ANARCO',
    email: 'monroe.gibbs@anarco.us',
    phone: '+1 (919) 523-2250',
    address: '357 Dank Court, Chloride, Guam, 1791',
    about:
      'Sint dolor ad adipisicing enim fugiat duis. Veniam incididunt ut laboris nisi aliqua incididunt proident duis nisi Lorem adipisicing et. Laboris voluptate minim cillum proident eiusmod sint anim. Consectetur mollit deserunt do occaecat cupidatat tempor do reprehenderit sunt aute ut veniam ullamco. Aliquip sit excepteur ex mollit duis esse. Cupidatat ipsum laborum cillum aute nisi irure voluptate esse nostrud nulla do qui.',
    registered: 'Sunday, August 6, 2017 2:34 PM',
    latitude: '-78.334808',
    longitude: '-54.971123',
    tags: ['aliquip', 'exercitation', 'in', 'esse', 'dolor'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Sybil Herring',
      },
      {
        id: 1,
        name: 'Pena Daniel',
      },
      {
        id: 2,
        name: 'Sellers Macdonald',
      },
    ],
    greeting: 'Hello, Monroe! You have 8 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '5c1d5125d30088b5ad55d663',
    index: 2,
    guid: '6c1dd33b-79f7-471b-be02-9fcdcdf7352c',
    isActive: false,
    balance: '$1,091.84',
    picture: 'http://placehold.it/32x32',
    age: 39,
    eyeColor: 'blue',
    name: {
      first: 'Charlene',
      last: 'Dotson',
    },
    company: 'TECHMANIA',
    email: 'charlene.dotson@techmania.com',
    phone: '+1 (922) 545-2119',
    address: '701 Fiske Place, Brewster, Virgin Islands, 5348',
    about:
      'Laboris aliquip ex consequat duis. Incididunt et laboris velit ipsum. Cillum nulla aute eu qui incididunt minim deserunt ullamco velit. Occaecat enim eu ex do aliqua sit. Id culpa ea labore dolor incididunt in ad eiusmod fugiat minim. Id ad excepteur laborum fugiat ex mollit.',
    registered: 'Sunday, June 26, 2016 6:15 PM',
    latitude: '15.117944',
    longitude: '-37.21466',
    tags: ['minim', 'do', 'tempor', 'et', 'tempor'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Burch Dudley',
      },
      {
        id: 1,
        name: 'Taylor Bradford',
      },
      {
        id: 2,
        name: 'Burton Brennan',
      },
    ],
    greeting: 'Hello, Charlene! You have 10 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '5c1d5125963396c84db3c2e0',
    index: 3,
    guid: '616c76f8-56df-41c6-bbd9-bd414fcadc14',
    isActive: false,
    balance: '$1,146.36',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'green',
    name: {
      first: 'Maddox',
      last: 'Chan',
    },
    company: 'INSURITY',
    email: 'maddox.chan@insurity.name',
    phone: '+1 (880) 402-2289',
    address: '116 Wythe Avenue, Kilbourne, Oregon, 1806',
    about:
      'Ea eu voluptate sunt commodo aute culpa qui do amet enim nulla excepteur. Pariatur exercitation ut sint aliqua amet fugiat deserunt commodo laborum amet. Aute voluptate amet non fugiat magna ea est laborum elit magna Lorem consectetur Lorem excepteur.',
    registered: 'Thursday, June 9, 2016 2:44 PM',
    latitude: '14.830267',
    longitude: '75.418401',
    tags: ['laboris', 'tempor', 'mollit', 'proident', 'aliqua'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Nolan Silva',
      },
      {
        id: 1,
        name: 'Hardy Gentry',
      },
      {
        id: 2,
        name: 'Mendez Bass',
      },
    ],
    greeting: 'Hello, Maddox! You have 7 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5c1d5125a0ea44a92fa747e4',
    index: 4,
    guid: '77ad319a-1b03-4936-ae70-7ae168dfee68',
    isActive: false,
    balance: '$1,820.02',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'blue',
    name: {
      first: 'Harriet',
      last: 'Bolton',
    },
    company: 'ONTALITY',
    email: 'harriet.bolton@ontality.info',
    phone: '+1 (957) 516-3516',
    address: '431 Lombardy Street, Manchester, Pennsylvania, 161',
    about:
      'Ullamco laboris laboris irure velit elit dolore commodo. Ut mollit nulla consectetur nisi nisi in incididunt. Labore enim incididunt consectetur commodo id. Sit fugiat dolor quis amet aliqua aliquip ut. Aliqua nulla elit excepteur dolor. Quis laboris excepteur consequat ipsum cupidatat magna culpa.',
    registered: 'Sunday, July 31, 2016 10:16 AM',
    latitude: '12.980598',
    longitude: '165.643823',
    tags: ['duis', 'veniam', 'aliquip', 'deserunt', 'duis'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Effie Kramer',
      },
      {
        id: 1,
        name: 'Wilda Moss',
      },
      {
        id: 2,
        name: 'Katie Brown',
      },
    ],
    greeting: 'Hello, Harriet! You have 10 unread messages.',
    favoriteFruit: 'apple',
  },
]
